### ISSUE TITLE
IndexOutOfBoundsException when measureScrapChild with support 23.4.0

### ISSUE THREAD

**Issue by wilsonssss** [Ekirapapaul/Expandable-Recyclerview#1]
screenshots:
<img src="https://res.cloudinary.com/dsjgmeuyi/image/upload/v1466322452/l5y3dltiqqbje6lf7of7.png"/>

```

CustomLinearLayoutManager: measureScrapChild: java.lang.IndexOutOfBoundsException: Invalid item position 0(0). Item count:0
 java.lang.IndexOutOfBoundsException: Invalid item position 0(0). Item count:0
     at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4622)
     at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4617)
     at com.vorane.recyclerview.CustomLinearLayoutManager.measureScrapChild(CustomLinearLayoutManager.java:73)
     at com.vorane.recyclerview.CustomLinearLayoutManager.onMeasure(CustomLinearLayoutManager.java:36)
     at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:2614)
     at android.view.View.measure(View.java:17444)
     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5464)
     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
     at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
     at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
     at android.view.View.measure(View.java:17444)
     at android.support.v7.widget.RecyclerView$LayoutManager.measureChildWithMargins(RecyclerView.java:7487)
     at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1416)
     at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1353)
     at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:574)
     at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3028)
     at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:2625)
     at android.view.View.measure(View.java:17444)
     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5464)
     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
     at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
     at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
     at android.view.View.measure(View.java:17444)
     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5464)
     at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
     at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
     at android.view.View.measure(View.java:17444)
     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5464)
     at android.support.v7.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:391)
     at android.view.View.measure(View.java:17444)
     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5464)
     at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
     at android.view.View.measure(View.java:17444)
     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5464)
     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
     at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
     at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
     at android.view.View.measure(View.java:17444)
     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5464)
     at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
     at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2563)
     at android.view.View.measure(View.java:17444)
     at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2028)
     at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1193)
     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1399)
     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1081)
     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5818)
     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:769)
     at android.view.Choreographer.doCallbacks(Choreographer.java:582)
     at android.view.Choreographer.doFrame(Choreographer.java:552)
     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:755)
     at android.os.Handler.handleCallback(Handler.java:739)
     at android.os.Handler.dispatchMessage(Handler.java:95)
     at android.os.Looper.loop(Looper.java:135)
    at android.a
```

**Comment by Ekirapapaul** [comment]
Kindly, what data did you pass to the adapters?
